version: "3"

services:
  phoenix:
    build: .
    volumes:
      - './apps:/yic/apps'
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - /var/lib/postgresql/data
  web:
    build: ./docker/web
    volumes:
      - ./target:/usr/local/apache2/htdocs
    ports:
      - "8080:80"
    depends_on: 
      - phoenix