# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     Yic.Repo.insert!(%Yic.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias Yic.Repo
alias Yic.Iam.Users
alias Yic.Iam.Account
alias Yic.Forms.Datadef
alias Yic.Forms.Form
alias Yic.Apis.Api

Repo.insert! %Users{ email: "admin@example.com", firstname: "ad", lastname: "ministrator" }
Repo.insert! %Account{ login: "admin", hashed_password: Pbkdf2.hash_pwd_salt("admin"), user_id: 1, confirmed_at: NaiveDateTime.local_now }

# Repo.insert! %Datadef{ name: "", comment: "", version: "", definition: '' }
json1 = "{\"root\": \"datadef\", \"datatypes\": [{\"name\": \"datadef\", \"type\": \"form\", \"fields\": [{\"field\": \"id\", \"required\": false}, {\"field\": \"comment\", \"required\": true}, {\"field\": \"definition\", \"required\": true}, {\"field\": \"name\", \"required\": true}, {\"field\": \"version\", \"required\": true}], \"basetype\": \"map\"}, {\"name\": \"comment\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"definition\", \"type\": \"map\", \"fields\": [{\"field\": \"action\", \"required\": false}, {\"field\": \"saveaction\", \"required\": false}, {\"field\": \"createaction\", \"required\": false}, {\"field\": \"type\", \"required\": true}, {\"field\": \"elements\", \"required\": true}, {\"field\": \"title\", \"required\": true}], \"basetype\": \"string\"}, {\"name\": \"id\", \"basetype\": \"number\", \"validations\": []}, {\"name\": \"action\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"saveaction\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"createaction\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"type\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"elements\", \"basetype\": \"array\", \"validations\": []}, {\"name\": \"title\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"label\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"name\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"version\", \"basetype\": \"string\", \"validations\": [{\"rule\": \"^(\\\\d+\\\\.)?(\\\\d+\\\\.)?(\\\\*|\\\\d+)$\", \"type\": \"format\", \"error\": \"Invalid version format.\"}]}]}"
Repo.insert! %Datadef{ name: "datadef", comment: "Data definition for datadef", version: "1.0", definition: json1 }
json2 = "{\"root\": \"form\", \"datatypes\": [{\"name\": \"form\", \"type\": \"form\", \"fields\": [{\"field\": \"id\", \"required\": false}, {\"field\": \"comment\", \"required\": true}, {\"field\": \"definition\", \"required\": true}, {\"field\": \"name\", \"required\": true}, {\"field\": \"version\", \"required\": true}, {\"field\": \"author\", \"required\": false}], \"basetype\": \"map\"}, {\"name\": \"comment\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"definition\", \"type\": \"map\", \"fields\": [{\"field\": \"action\", \"required\": false}, {\"field\": \"saveaction\", \"required\": false}, {\"field\": \"createaction\", \"required\": false}, {\"field\": \"type\", \"required\": true}, {\"field\": \"elements\", \"required\": true}, {\"field\": \"title\", \"required\": true}], \"basetype\": \"string\"}, {\"name\": \"id\", \"basetype\": \"number\", \"validations\": []}, {\"name\": \"action\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"saveaction\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"createaction\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"type\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"elements\", \"basetype\": \"array\", \"validations\": []}, {\"name\": \"title\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"label\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"name\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"version\", \"basetype\": \"string\", \"validations\": [{\"rule\": \"^(\\\\d+\\\\.)?(\\\\d+\\\\.)?(\\\\*|\\\\d+)$\", \"type\": \"format\", \"error\": \"Invalid version format.\"}]}, {\"name\": \"author\", \"basetype\": \"id\", \"validations\": []}]}"
Repo.insert! %Datadef{ name: "form", comment: "Data definition for forms", version: "1.0", definition: json2 }
json3 = "{\"root\": \"user\", \"datatypes\": [{\"name\": \"user\", \"type\": \"form\", \"fields\": [{\"field\": \"id\", \"required\": false}, {\"field\": \"firstname\", \"required\": true}, {\"field\": \"lastname\", \"required\": true}, {\"field\": \"email\", \"required\": true}], \"basetype\": \"map\"}, {\"name\": \"firstname\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"id\", \"basetype\": \"number\", \"validations\": []}, {\"name\": \"lastname\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"email\", \"basetype\": \"string\", \"validations\": []}, {\"name\": \"createaction\", \"basetype\": \"string\", \"validations\": []}]}"
Repo.insert! %Datadef{ name: "user", comment: "Data definition for users", version: "1.0", definition: json3 }

# Repo.insert! %Form{ name: "", comment: "", version: "", definition: "" }
Repo.insert! %Form{ name: "listdatadef", comment: "List view of all data definitions", version: "1.0", definition: "{\"type\": \"overview\", \"title\": \"Data definition overview\", \"actions\": [{\"list\": {\"url\": \"apis/datadefs\"}}, {\"edit\": {\"url\": \"apis/datadefs/:id\"}}, {\"delete\": {\"url\": \"api/forms/datadefs/:id\"}}], \"elements\": [{\"pk\": true, \"type\": \"hidden\", \"datapath\": \"id\"}, {\"type\": \"text\", \"label\": \"Name\", \"datapath\": \"name\"}, {\"type\": \"text\", \"label\": \"Version\", \"datapath\": \"version\"}, {\"type\": \"text\", \"label\": \"Comment\", \"datapath\": \"comment\"}], \"globalValidations\": []}"}
Repo.insert! %Form{ name: "listform", comment: "List view of all forms", version: "1.0", definition: "{\"type\": \"overview\", \"title\": \"Form overview\", \"actions\": [{\"list\": {\"url\": \"apis/forms\"}}, {\"edit\": {\"url\": \"apis/forms/:id\"}}, {\"delete\": {\"url\": \"api/forms/forms/:id\"}}], \"elements\": [{\"pk\": true, \"type\": \"hidden\", \"datapath\": \"id\"}, {\"type\": \"text\", \"label\": \"Name\", \"datapath\": \"name\"}, {\"type\": \"text\", \"label\": \"Version\", \"datapath\": \"version\"}, {\"type\": \"text\", \"label\": \"Comment\", \"datapath\": \"comment\"}], \"globalValidations\": []}"}
Repo.insert! %Form{ name: "detailuser", comment: "Edit form for user", version: "1.0", definition: "{\"type\": \"detail\", \"title\": \"User detail\", \"actions\": [{\"create\": {\"url\": \"/iam/users\"}}, {\"save\": {\"url\": \"/iam/users/:id\"}}], \"elements\": [{\"type\": \"hidden\", \"datapath\": \"id\"}, {\"type\": \"text\", \"label\": \"Fist Name\", \"datapath\": \"firstname\"}, {\"type\": \"text\", \"label\": \"Last name\", \"datapath\": \"lastname\"}, {\"type\": \"text\", \"label\": \"email address\", \"datapath\": \"email\"}], \"saveaction\": \"/iam/users/:id\", \"globalValidations\": []}"}
Repo.insert! %Form{ name: "detailsform", comment: "Edit view for form defintion", version: "1.0", definition: "{\"type\": \"detail\", \"title\": \"Form detail\", \"actions\": [{\"create\": {\"url\": \"/forms/forms\"}}, {\"save\": {\"url\": \"/forms/forms/:id\"}}], \"elements\": [{\"type\": \"hidden\", \"datapath\": \"id\"}, {\"type\": \"text\", \"label\": \"Form Name\", \"datapath\": \"name\"}, {\"type\": \"text\", \"label\": \"Version\", \"datapath\": \"version\"}, {\"type\": \"text\", \"label\": \"Comment\", \"datapath\": \"comment\"}, {\"type\": \"number\", \"label\": \"Author\", \"datapath\": \"author\"}, {\"type\": \"json\", \"label\": \"Definition\", \"datapath\": \"definition\"}], \"saveaction\": \"/forms/forms/:id\", \"globalValidations\": []}"}
Repo.insert! %Form{ name: "listuser", comment: "list view of all users", version: "1.0", definition: "{\"type\": \"overview\", \"title\": \"User overview\", \"actions\": [{\"list\": {\"url\": \"apis/users\", \"label\": \"Show users\"}}, {\"edit\": {\"url\": \"apis/users/:id\", \"label\": \"Edit\"}}, {\"create\": {\"url\": \"apis/users\", \"label\": \"New\"}}, {\"delete\": {\"url\": \"iam/users\", \"label\": \"Delete\"}}], \"elements\": [{\"pk\": true, \"type\": \"hidden\", \"datapath\": \"id\"}, {\"type\": \"text\", \"label\": \"First name\", \"datapath\": \"firstname\"}, {\"type\": \"text\", \"label\": \"Last name\", \"datapath\": \"lastname\"}, {\"type\": \"text\", \"label\": \"email address\", \"datapath\": \"email\"}], \"getaction\": \"apis/users\", \"globalValidations\": []}"}
Repo.insert! %Form{ name: "detaildatadef", comment: "Edit form for data definition", version: "1.0", definition: "{\"type\": \"detail\", \"title\": \"Data definition detail\", \"actions\": [{\"create\": {\"url\": \"/forms/datadefs\"}}, {\"save\": {\"url\": \"/forms/datadefs/:id\"}}], \"elements\": [{\"type\": \"hidden\", \"datapath\": \"id\"}, {\"type\": \"tabs\", \"elements\": [{\"type\": \"tab\", \"label\": \"Generic\", \"elements\": [{\"type\": \"grid\", \"count\": 2, \"elements\": [{\"type\": \"gridcol\", \"elements\": [{\"type\": \"text\", \"label\": \"Data definition name\", \"datapath\": \"name\"}, {\"type\": \"text\", \"label\": \"Version\", \"datapath\": \"version\"}]}, {\"type\": \"gridcol\", \"elements\": [{\"type\": \"textarea\", \"label\": \"Comment\", \"datapath\": \"comment\"}]}]}]}, {\"type\": \"tab\", \"label\": \"Definition\", \"elements\": [{\"type\": \"json\", \"label\": \"Definition\", \"datapath\": \"definition\"}]}]}], \"saveaction\": \"/forms/datadefs/:id\", \"globalValidations\": []}" }

# Repo.insert! %Api{ name: "", description: "", version: "1.0", request: "", definition: "" }
Repo.insert! %Api{ name: "Show form by id", description: "Get the data for the Edit Form (data, datadef and formdef)", version: "1.0", request: "apis/forms/:id", definition: "{\"output\": {\"data\": \"data\", \"datadef\": \"datadef\", \"formdef\": \"formdef\"}, \"actions\": [{\"url\": \"http://localhost:4000/api/forms/forms/:id\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"data\"}, {\"url\": \"http://localhost:4000/api/forms/datadefbyname/form\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"datadef\"}, {\"url\": \"http://localhost:4000/api/forms/formbyname/detailsform\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"formdef\"}]}" }
Repo.insert! %Api{ name: "List all users", description: "Get the data for list Users (data, datadef and formdef)", version: "1.0", request: "apis/users", definition: "{\"output\": {\"data\": \"data\", \"datadef\": \"datadef\", \"formdef\": \"formdef\"}, \"actions\": [{\"url\": \"http://localhost:4000/api/iam/users\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"data\"}, {\"url\": \"http://localhost:4000/api/forms/datadefbyname/user\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"datadef\"}, {\"url\": \"http://localhost:4000/api/forms/formbyname/listuser\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"formdef\"}]}" }
Repo.insert! %Api{ name: "Show user by id", description: "Get the data for the edit form (data, datadef and formdef)", version: "1.0", request: "apis/users/:id", definition: "{\"output\": {\"data\": \"data\", \"datadef\": \"datadef\", \"formdef\": \"formdef\"}, \"actions\": [{\"url\": \"http://localhost:4000/api/iam/users/:id\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"data\"}, {\"url\": \"http://localhost:4000/api/forms/datadefbyname/user\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"datadef\"}, {\"url\": \"http://localhost:4000/api/forms/formbyname/detailuser\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"formdef\"}]}" }
Repo.insert! %Api{ name: "Show datadef by id", description: "Get the data for Data def forms", version: "1.0", request: "apis/datadefs/:id", definition: "{\"output\": {\"data\": \"data\", \"datadef\": \"datadef\", \"formdef\": \"formdef\"}, \"actions\": [{\"url\": \"http://localhost:4000/api/forms/datadefs/:id\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"data\"}, {\"url\": \"http://localhost:4000/api/forms/datadefbyname/datadef\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"datadef\"}, {\"url\": \"http://localhost:4000/api/forms/formbyname/detaildatadef\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"formdef\"}]}" }
Repo.insert! %Api{ name: "List all forms", description: "Get the data for List Forms (data, datadef and formdef)", version: "1.0", request: "apis/forms", definition: "{\"output\": {\"data\": \"data\", \"datadef\": \"datadef\", \"formdef\": \"formdef\"}, \"actions\": [{\"url\": \"http://localhost:4000/api/forms/forms\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"data\"}, {\"url\": \"http://localhost:4000/api/forms/datadefbyname/form\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"datadef\"}, {\"url\": \"http://localhost:4000/api/forms/formbyname/listform\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"formdef\"}]}" }
Repo.insert! %Api{ name: "List all data definitions", description: "Get the data for List data definitions", version: "1.0", request: "apis/datadefs", definition: "{\"output\": {\"data\": \"data\", \"datadef\": \"datadef\", \"formdef\": \"formdef\"}, \"actions\": [{\"url\": \"http://localhost:4000/api/forms/datadefs\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"data\"}, {\"url\": \"http://localhost:4000/api/forms/datadefbyname/datadef\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"datadef\"}, {\"url\": \"http://localhost:4000/api/forms/formbyname/listdatadef\", \"token\": \"jwt_local\", \"method\": \"get\", \"output\": \"formdef\"}]}" }
