# ./Dockerfile
# Extend from the official Elixir image
# docker pull bitwalker/alpine-elixir-phoenix:1.12.3
FROM elixir:1.12.3

RUN apt-get update -y
RUN apt-get install -y build-essential inotify-tools postgresql-client git curl && apt-get clean

# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# nvm environment variables
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 4.4.7

# install nvm
# https://github.com/creationix/nvm#install-script
RUN curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash

# install node and npm
RUN source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

# add node and npm to path so the commands are available
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

# confirm installation
RUN node -v
RUN npm -v

# Install hex package manager
RUN mix local.hex --force
RUN mix local.rebar --force

# copy relevant files - add using Upload
ADD entrypoint.sh ./

# Create required directories
RUN mkdir /yic
RUN git clone https://github.com/schaafie/yic.git
WORKDIR /yic

# Build the application
RUN mix deps.get
RUN mix deps.compile